<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdditionalComments', 'doctrine');

/**
 * BaseAdditionalComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $grade_id
 * @property string $additional_comment
 * @property Grade $Grade
 * 
 * @method integer            getId()                 Returns the current record's "id" value
 * @method integer            getGradeId()            Returns the current record's "grade_id" value
 * @method string             getAdditionalComment()  Returns the current record's "additional_comment" value
 * @method Grade              getGrade()              Returns the current record's "Grade" value
 * @method AdditionalComments setId()                 Sets the current record's "id" value
 * @method AdditionalComments setGradeId()            Sets the current record's "grade_id" value
 * @method AdditionalComments setAdditionalComment()  Sets the current record's "additional_comment" value
 * @method AdditionalComments setGrade()              Sets the current record's "Grade" value
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdditionalComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('additional_comments');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('grade_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('additional_comment', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grade', array(
             'local' => 'grade_id',
             'foreign' => 'id'));
    }
}