<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClassRoom', 'doctrine');

/**
 * BaseClassRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $site_id
 * @property string $class_room_name
 * @property integer $is_active
 * @property Site $Site
 * @property Doctrine_Collection $Course
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getSiteId()          Returns the current record's "site_id" value
 * @method string              getClassRoomName()   Returns the current record's "class_room_name" value
 * @method integer             getIsActive()        Returns the current record's "is_active" value
 * @method Site                getSite()            Returns the current record's "Site" value
 * @method Doctrine_Collection getCourse()          Returns the current record's "Course" collection
 * @method ClassRoom           setId()              Sets the current record's "id" value
 * @method ClassRoom           setSiteId()          Sets the current record's "site_id" value
 * @method ClassRoom           setClassRoomName()   Sets the current record's "class_room_name" value
 * @method ClassRoom           setIsActive()        Sets the current record's "is_active" value
 * @method ClassRoom           setSite()            Sets the current record's "Site" value
 * @method ClassRoom           setCourse()          Sets the current record's "Course" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('class_room');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('site_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('class_room_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id'));

        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'class_room_id'));
    }
}