<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $person_id
 * @property integer $role_id
 * @property integer $is_active
 * @property Person $Person
 * @property Role $Role
 * @property Doctrine_Collection $Course
 * @property Doctrine_Collection $Evaluation
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getPersonId()   Returns the current record's "person_id" value
 * @method integer             getRoleId()     Returns the current record's "role_id" value
 * @method integer             getIsActive()   Returns the current record's "is_active" value
 * @method Person              getPerson()     Returns the current record's "Person" value
 * @method Role                getRole()       Returns the current record's "Role" value
 * @method Doctrine_Collection getCourse()     Returns the current record's "Course" collection
 * @method Doctrine_Collection getEvaluation() Returns the current record's "Evaluation" collection
 * @method User                setId()         Sets the current record's "id" value
 * @method User                setPersonId()   Sets the current record's "person_id" value
 * @method User                setRoleId()     Sets the current record's "role_id" value
 * @method User                setIsActive()   Sets the current record's "is_active" value
 * @method User                setPerson()     Sets the current record's "Person" value
 * @method User                setRole()       Sets the current record's "Role" value
 * @method User                setCourse()     Sets the current record's "Course" collection
 * @method User                setEvaluation() Sets the current record's "Evaluation" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Evaluation', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}