<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Schedule', 'doctrine');

/**
 * BaseSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property time $start
 * @property time $end
 * @property string $description
 * @property integer $is_active
 * @property Doctrine_Collection $Course
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method time                getStart()       Returns the current record's "start" value
 * @method time                getEnd()         Returns the current record's "end" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getIsActive()    Returns the current record's "is_active" value
 * @method Doctrine_Collection getCourse()      Returns the current record's "Course" collection
 * @method Schedule            setId()          Sets the current record's "id" value
 * @method Schedule            setStart()       Sets the current record's "start" value
 * @method Schedule            setEnd()         Sets the current record's "end" value
 * @method Schedule            setDescription() Sets the current record's "description" value
 * @method Schedule            setIsActive()    Sets the current record's "is_active" value
 * @method Schedule            setCourse()      Sets the current record's "Course" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schedule');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('start', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'schedule_id'));
    }
}