<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Link', 'doctrine');

/**
 * BaseLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $student_id
 * @property string $token
 * @property timestamp $expiration_date
 * @property integer $is_active
 * @property Student $Student
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method integer   getStudentId()       Returns the current record's "student_id" value
 * @method string    getToken()           Returns the current record's "token" value
 * @method timestamp getExpirationDate()  Returns the current record's "expiration_date" value
 * @method integer   getIsActive()        Returns the current record's "is_active" value
 * @method Student   getStudent()         Returns the current record's "Student" value
 * @method Link      setId()              Sets the current record's "id" value
 * @method Link      setStudentId()       Sets the current record's "student_id" value
 * @method Link      setToken()           Sets the current record's "token" value
 * @method Link      setExpirationDate()  Sets the current record's "expiration_date" value
 * @method Link      setIsActive()        Sets the current record's "is_active" value
 * @method Link      setStudent()         Sets the current record's "Student" value
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('link');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('token', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('expiration_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id'));
    }
}