<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Level', 'doctrine');

/**
 * BaseLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $level_name
 * @property integer $is_active
 * @property Doctrine_Collection $Course
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getLevelName()  Returns the current record's "level_name" value
 * @method integer             getIsActive()   Returns the current record's "is_active" value
 * @method Doctrine_Collection getCourse()     Returns the current record's "Course" collection
 * @method Level               setId()         Sets the current record's "id" value
 * @method Level               setLevelName()  Sets the current record's "level_name" value
 * @method Level               setIsActive()   Sets the current record's "is_active" value
 * @method Level               setCourse()     Sets the current record's "Course" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('level');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('level_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'level_id'));
    }
}