<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Question', 'doctrine');

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $question_name
 * @property decimal $score
 * @property string $description
 * @property integer $is_active
 * @property Doctrine_Collection $Checkboxes
 * @property Doctrine_Collection $Grade
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getQuestionName()  Returns the current record's "question_name" value
 * @method decimal             getScore()         Returns the current record's "score" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method integer             getIsActive()      Returns the current record's "is_active" value
 * @method Doctrine_Collection getCheckboxes()    Returns the current record's "Checkboxes" collection
 * @method Doctrine_Collection getGrade()         Returns the current record's "Grade" collection
 * @method Question            setId()            Sets the current record's "id" value
 * @method Question            setQuestionName()  Sets the current record's "question_name" value
 * @method Question            setScore()         Sets the current record's "score" value
 * @method Question            setDescription()   Sets the current record's "description" value
 * @method Question            setIsActive()      Sets the current record's "is_active" value
 * @method Question            setCheckboxes()    Sets the current record's "Checkboxes" collection
 * @method Question            setGrade()         Sets the current record's "Grade" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('question_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('score', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Checkboxes', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('Grade', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}