<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Site', 'doctrine');

/**
 * BaseSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $site_name
 * @property string $panel_color
 * @property integer $is_active
 * @property Doctrine_Collection $ClassRoom
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getSiteName()    Returns the current record's "site_name" value
 * @method string              getPanelColor()  Returns the current record's "panel_color" value
 * @method integer             getIsActive()    Returns the current record's "is_active" value
 * @method Doctrine_Collection getClassRoom()   Returns the current record's "ClassRoom" collection
 * @method Site                setId()          Sets the current record's "id" value
 * @method Site                setSiteName()    Sets the current record's "site_name" value
 * @method Site                setPanelColor()  Sets the current record's "panel_color" value
 * @method Site                setIsActive()    Sets the current record's "is_active" value
 * @method Site                setClassRoom()   Sets the current record's "ClassRoom" collection
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('site_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('panel_color', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClassRoom', array(
             'local' => 'id',
             'foreign' => 'site_id'));
    }
}