<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Checkboxes', 'doctrine');

/**
 * BaseCheckboxes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property string $checkbox_name
 * @property integer $is_active
 * @property Question $Question
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method integer    getQuestionId()    Returns the current record's "question_id" value
 * @method string     getCheckboxName()  Returns the current record's "checkbox_name" value
 * @method integer    getIsActive()      Returns the current record's "is_active" value
 * @method Question   getQuestion()      Returns the current record's "Question" value
 * @method Checkboxes setId()            Sets the current record's "id" value
 * @method Checkboxes setQuestionId()    Sets the current record's "question_id" value
 * @method Checkboxes setCheckboxName()  Sets the current record's "checkbox_name" value
 * @method Checkboxes setIsActive()      Sets the current record's "is_active" value
 * @method Checkboxes setQuestion()      Sets the current record's "Question" value
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckboxes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('checkboxes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('checkbox_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));
    }
}