checkboxes:
  class: sfDoctrineRouteCollection
  options:
    model:                Checkboxes
    module:               checkboxes
    prefix_path:          /checkboxes
    column:               id
    with_wildcard_routes: true

additional_comments:
  class: sfDoctrineRouteCollection
  options:
    model:                AdditionalComments
    module:               additional_comments
    prefix_path:          /additional_comments
    column:               id
    with_wildcard_routes: true

link:
  class: sfDoctrineRouteCollection
  options:
    model:                link
    module:               link
    prefix_path:          /link
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

student:
  class: sfDoctrineRouteCollection
  options:
    model:                Student
    module:               student
    prefix_path:          /student
    column:               id
    with_wildcard_routes: true

site:
  class: sfDoctrineRouteCollection
  options:
    model:                Site
    module:               site
    prefix_path:          /site
    column:               id
    with_wildcard_routes: true

schedule_per_site:
  class: sfDoctrineRouteCollection
  options:
    model:                SchedulePerSite
    module:               schedule_per_site
    prefix_path:          /schedule_per_site
    column:               id
    with_wildcard_routes: true

schedule:
  class: sfDoctrineRouteCollection
  options:
    model:                Schedule
    module:               schedule
    prefix_path:          /schedule
    column:               id
    with_wildcard_routes: true

role:
  class: sfDoctrineRouteCollection
  options:
    model:                Role
    module:               role
    prefix_path:          /role
    column:               id
    with_wildcard_routes: true

question:
  class: sfDoctrineRouteCollection
  options:
    model:                Question
    module:               question
    prefix_path:          /question
    column:               id
    with_wildcard_routes: true

person:
  class: sfDoctrineRouteCollection
  options:
    model:                Person
    module:               person
    prefix_path:          /person
    column:               id
    with_wildcard_routes: true

level:
  class: sfDoctrineRouteCollection
  options:
    model:                Level
    module:               level
    prefix_path:          /level
    column:               id
    with_wildcard_routes: true

inscription:
  class: sfDoctrineRouteCollection
  options:
    model:                Inscription
    module:               inscription
    prefix_path:          /inscription
    column:               id
    with_wildcard_routes: true

grade:
  class: sfDoctrineRouteCollection
  options:
    model:                Grade
    module:               grade
    prefix_path:          /grade
    column:               id
    with_wildcard_routes: true

exam:
  class: sfDoctrineRouteCollection
  options:
    model:                Exam
    module:               exam
    prefix_path:          /exam
    column:               id
    with_wildcard_routes: true

evaluation:
  class: sfDoctrineRouteCollection
  options:
    model:                Evaluation
    module:               evaluation
    prefix_path:          /evaluation
    column:               id
    with_wildcard_routes: true

course:
  class: sfDoctrineRouteCollection
  options:
    model:                Course
    module:               course
    prefix_path:          /course
    column:               id
    with_wildcard_routes: true

class_room:
  class: sfDoctrineRouteCollection
  options:
    model:                ClassRoom
    module:               class_room
    prefix_path:          /class_room
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
