<?php

/**
 * AdditionalCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdditionalCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdditionalCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdditionalComments');
    }
}