<?php

/**
 * CheckboxesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckboxesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CheckboxesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Checkboxes');
    }
}