<?php

/**
 * ClassRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassRoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassRoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClassRoom');
    }
}