<?php

/**
 * Course
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Course extends BaseCourse {

    public function getTotalInscription() {
        $iTotalInscription = 0;
        foreach ($this->getInscription() as $oInscription) {
            if ($oInscription->getIsActive() == 1) {
                $iTotalInscription++;
            }
        }
        return $iTotalInscription;
    }

}
