<?php

/**
 * Grade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Grade extends BaseGrade {

    public function getPanelClass() {
        if ($this->getGradeScore() == 2) {
            return "panel-success";
        } elseif ($this->getGradeScore() == 1.5) {
            return "panel-info";
        } elseif ($this->getGradeScore() == 1) {
            return "panel-warning";
        } else {
            return "panel-danger";
        }
    }

    public function getGradeColor() {
        if ($this->getGradeScore() == 2) {
            return "#5cb85c";
        } elseif ($this->getGradeScore() == 1.5) {
            return "#a9c0f0";
        } elseif ($this->getGradeScore() == 1) {
            return "#f0ad4e";
        } else {
            return "#d9534f";
        }        
    }

}
