<?php

/**
 * InscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inscription');
    }
}