<?php

/**
 * PersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PersonTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Person');
    }

    public function isValidEmail($iPersonID, $sEmail) {
        $sEmailOtherPerson = "select count(p.id) as counter from person p"
                . " where p.id not in ({$iPersonID}) and p.email = '{$sEmail}'";
        $aResult = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sEmailOtherPerson);
        return $aResult[0]["counter"] == 0;
    }

    public function isValidUsername($iPersonID, $sUsername) {
        $sEmailOtherPerson = "select count(p.id) as counter from person p"
                . " where p.id not in ({$iPersonID}) and p.username = '{$sUsername}'";
        $aResult = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sEmailOtherPerson);
        return $aResult[0]["counter"] == 0;
    }

}
