<?php

/**
 * Schedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Schedule extends BaseSchedule {

    public function getScheduleName() {
        $dateTimeStart = new DateTime($this->getStart());
        $start_time = date_format($dateTimeStart, "h:i a");

        $dateTimeEnd = new DateTime($this->getEnd());
        $end_time = date_format($dateTimeEnd, "h:i a");

        $description = $this->getDescription() != null ? " (" . $this->getDescription() . ")" : "";
        $scheduleName = $start_time . " - " . $end_time . $description;

        return $scheduleName;
    }

}
