<?php

/**
 * Student
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e4cc
 * @subpackage model
 * @author     jorgezfx@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Student extends BaseStudent {

    public function isActive() {
        return $this->getIsActive() == 1 ? true : false;
    }

    /**
     * @license http://opensource.org/licenses/gpl-license.php GNU Public License
     * @version 1.0
     * @author Miguel Cubias <cubiascaceres@gmail.com>
     * @return \Evaluation the lastest evaluation perform fot the student
     */
    public function getLastEvaluation() {
        $oLastEvaluation = new Evaluation();
        foreach ($this->getInscription() as $oInscription) {
            foreach ($oInscription->getEvaluation() as $oEvaluation) {
                if ($oLastEvaluation->isNew()) {
                    $oLastEvaluation = $oEvaluation;
                } 
                if ($oEvaluation->getEvaluationDate() > $oLastEvaluation->getEvaluationDate()) {
                    $oLastEvaluation = $oEvaluation;
                }
            }
        }
        return $oLastEvaluation;
    }

}
