# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:              English 4 Call Centers, Evaluation System
    description:  System to keep track of all students and their grades
    keywords:     e4cc, english, symfony, evaluation, grades, login
    language:     en
    autor:           Symfony 1.4
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, font-awesome.min.css, metisMenu.min.css, sb-admin-2.css, jquery.growl.css]

  javascripts:    [jquery.min.js, bootstrap.min.js, metisMenu.min.js, sb-admin-2.js, md5_encrypt.js, sha1_encrypt, custom_validator, jquery.growl.js]

  has_layout:     true
  layout:         login_layout
